version: "3"

services:
  client:
    build: ./client
    container_name: client
    ports:
      - 8080:8080
    depends_on: 
      - server

  server:
    build: ./server
    container_name: server
    ports:
      - 5000:5000
    depends_on: 
      - mongo
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    restart: always
